import React from 'react';
import PropTypes from 'prop-types';
import { withStyles } from '@material-ui/core/styles';
import Grid from '@material-ui/core/Grid';
import Container from '@material-ui/core/Container';
import Typography from '../components/Typography';
import {ReactComponent as VideoCallSvg} from "../../static/video-call.svg";
import {ReactComponent as DiscoverSvg} from "../../static/discover.svg";
import {ReactComponent as TrustSvg} from "../../static/trust.svg";
import {ReactComponent as CalendarSvg} from "../../static/calendar.svg";

const styles = theme => ({
  root: {
    display: 'flex',
    overflow: 'hidden',
    backgroundColor: theme.palette.secondary.light,
  },
  container: {
    marginTop: theme.spacing(15),
    marginBottom: theme.spacing(30),
    display: 'flex',
    position: 'relative',
  },
  item: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: theme.spacing(0, 5),
  },
  image: {
    height: 55,
  },
  title: {
    marginTop: theme.spacing(5),
    marginBottom: theme.spacing(5),
  },
  curvyLines: {
    pointerEvents: 'none',
    position: 'absolute',
    top: -180,
  },
});

function ProductValues(props) {
  const { classes } = props;

  return (
    <section className={classes.root}>
      <Container className={classes.container}>
        {/*<img*/}
        {/*  src="../../static/productCurvyLines.png"*/}
        {/*  className={classes.curvyLines}*/}
        {/*  alt="curvy lines"*/}
        {/*/>*/}
        <Grid container spacing={5}>
          <Grid item xs={12} md={4}>
            <div className={classes.item}>
              {/*<img*/}
              {/*  className={classes.image}*/}
              {/*  src="/static/themes/onepirate/productValues1.svg"*/}
              {/*  alt="suitcase"*/}
              {/*/>*/}
              <VideoCallSvg className={classes.image}/>
              <Typography variant="h6" className={classes.title}>
                Virtually connect
              </Typography>
              <Typography variant="h5">
                {'Join small group video calls generated by our data-driven '}
                {'approach to meet others who share your interests.'}
              </Typography>
            </div>
          </Grid>
          <Grid item xs={12} md={4}>
            <div className={classes.item}>
              {/*<img*/}
              {/*  className={classes.image}*/}
              {/*  src="/static/themes/onepirate/productValues2.svg"*/}
              {/*  alt="graph"*/}
              {/*/>*/}
              <DiscoverSvg className={classes.image}/>
              <Typography variant="h6" className={classes.title}>
                Personalization
              </Typography>
              <Typography variant="h5">
                {'Your conversations are real-time, dynamic, and tailored to '}
                {'your personality and hobbies.'}
              </Typography>
            </div>
          </Grid>
          <Grid item xs={12} md={4}>
            <div className={classes.item}>
              {/*<img*/}
              {/*  className={classes.image}*/}
              {/*  src="/static/themes/onepirate/productValues3.svg"*/}
              {/*  alt="clock"*/}
              {/*/>*/}
              <TrustSvg className={classes.image}/>
              <Typography variant="h6" className={classes.title}>
                Long-Lasting Bonds
              </Typography>
              <Typography variant="h5">
                {'Your conversations persist even after the call ends'}
                {', so you can stay in contact or start another call anytime.'}
              </Typography>
            </div>
          </Grid>
        </Grid>
      </Container>
    </section>
  );
}

ProductValues.propTypes = {
  classes: PropTypes.object.isRequired,
};

export default withStyles(styles)(ProductValues);
